
#ifndef INCLUDED_VMON_MSGS_H
#define INCLUDED_VMON_MSGS_H

typedef enum {
	VMON_MSG_PING_REQ=0xEA,
	VMON_MSG_PING_ACK=0xE5,

	VMON_MSG_FIXLEN_REQ=0xA5,
	VMON_MSG_VARLEN_REQ=0xA6,

	VMON_MSG_RSP_OK=0xE0,
	VMON_MSG_RSP_ERR=0xE1
} vmon_msgs_e;

#endif /* INCLUDED_VMON_MSGS_H */
